### ISSUE TITLE
How to protect uploads with Authentication

### ISSUE THREAD

**Issue by cberescu** [tus/tus-node-server#124]
Hi,  

Is there a way to not allow uploads without a proper authentication ? Or is there a way to stop an upload from being started. or an upload in progress ? 

Please help. Thanks.

**Comment by Acconut** [comment]
Yes, this is possible. Either you use a proxy and a middleware for your framework to check the authentication on the requests before forwarding them to tus-node-server.

Since you closed this issue on your own, I wanted to ask if you were able to help yourself?

**Comment by djsg** [comment]
If I use Apache as my proxy, is it achievable through configuration instead of coding?

**Comment by Acconut** [comment]
> If I use Apache as my proxy, is it achievable through configuration instead of coding?

Authentication should be handled by a proxy, such as Apache. I can't help you with Apache but there should be enough information available online to get you started with that.

> I guess between tus client and server, there is no authentication handshake, is there?

That's right, authentication is not handled by tus in any special way.

> I wonder how to link authentication to tus upload?

I don't fully understand the question but are you trying to link a *user* to a tus upload? If so, you can achieve this by using the metadata option in the tus client to attach a user ID to an upload. This can then be read by the tus server to find the corresponding user.

**Comment by djsg** [comment]
I am thinking of implementing what you suggested.
I will add a user ID in metadata at client side; in server's RequestValidator file, if userID key is not found, server invalidate client's request; if it is found, I will check if that use is authenticated, if not, invalidate it as well.
What's is the proper way to implement my logic without breaking the original server library code?
Can have some server configuration options to disable or enable the checks?

**Comment by Acconut** [comment]
> What's is the proper way to implement my logic without breaking the original server library code?

tus-node-server offers a event system but that cannot be used to invalidate requests as you want. The best way IMO would be to have a HTTP server as a wrapper around tus-node-server. This wrapper takes requests from the users, validates them and then passes the requests to tus-node-server if they are correct. This would work by invoking `Server#handle` with the request and response objects, similar to how the express example is constructed: https://github.com/tus/tus-node-server#use-tus-node-server-as-express-middleware. The exact details would vary depending on your setup/framework.

**Comment by djsg** [comment]
it's almost impossible for me to write a HTTP server wrapper, isn't it? 
What I can think of is to use Apache, which I am already using as proxy to tus server.
I will take a look at the express example and Apache authentication examples to get a clear picture.

**Comment by djsg** [comment]
@Acconut  Thank you for the advice. I will study the express sample and give it a try. Not familiar with it.

**Comment by djsg** [comment]
@Acconut  I tried the express wrapper code. 
Now I have a few more questions: 
is it true I can only put "my-token' in the metadata section? if it is, then
      if(req.headers["my-token"] !== "my_secret") {
will fail for request headers that do not have metadata section. This can be easily fixed by first checking if metatdata exists in the header; if so, then check "my-token".

However, what if none of the request headers contain metadata and "my-token"? How to check that. During my test, I saw 3 request headers triggering that if statement and metadata is in 2nd request. Is 3 a fixed number for TUS protocol?

**Comment by Acconut** [comment]
> is it true I can only put "my-token' in the metadata section? if it is, then
if(req.headers["my-token"] !== "my_secret") {

Watch out! This example does not read the upload metadata but just inspects a custom header. This header does not have to be called `my-token` but can have any name you want. [tus-js-client](https://github.com/tus/tus-js-client) (and most other clients) has a `header` option to allow you to specify your own headers. You should use headers for authentication/authorization since headers are included in all requests from tus but the upload metadata will only be included in one POST request (as you correctly noted in your previous comment).

> Is 3 a fixed number for TUS protocol?

No, not at all! the number of requests is completely variable and has no lower or upper limit. You should not rely on the number of requests.

**Comment by kokokenada** [comment]
@Acconut - a follow up question.  I'm picking up the user ID from a JWT 403ing unauthorized requests etc.  All good.  My question is how do I push the user ID obtaintained from the middleware down so that the server.on event handlers can get it?

**Comment by Acconut** [comment]
As far as I know, the triggered events to not have a reference to the corresponding request, so I don't think there is a direct way to get the ID from a middleware. However, you can set the upload metadata to contain the user ID when the upload is created and then examine the metadata in the events.
