### ISSUE TITLE
Impossible to disable CORS

### ISSUE THREAD

**Issue by samosvatov** [tus/tus-node-server#134]
On my project, all CORS are managed by ESP.
And I found out that this package adds 'Access-Control-Allow-Origin' header.
As an ESP.
Duplicating the same 'Access-Control-Allow-Origin' header leads to error.
Is it a possible way to disable this header in the package?

**Comment by Acconut** [comment]
As far as I know, there is no way to disable the CORS headers for tus-node-server as it's usually necessary to get it running. However, you may be able to remove the CORS headers using a proxy? I am not sure what ESP is, I have never heard that acronym in this context.

**Comment by saschbro** [comment]
I also stumbled over duplicate CORS header creation when `tus-node-server` is operated behind a reverse proxy. Because there seems to be no configuration option, I had to add a proxy configuration to remove the duplicate headers.

Another issue I recognized for operation behind a proxy / loadbalancer where request's `host header` is set to another value than origin server is that the `location header` is generated with the wrong domain. Because host part is taken from `host header`. Maybe it makes sense to add a configuration option for the header to take the domain optionally from, e.g. in my case `x-forwarded-host`.

I could provide a PR for both issues?

**Comment by Acconut** [comment]
> I also stumbled over duplicate CORS header creation when tus-node-server is operated behind a reverse proxy. Because there seems to be no configuration option, I had to add a proxy configuration to remove the duplicate headers.

Seems fair enough, I would be happy to accept a PR for that.

> Another issue I recognized for operation behind a proxy / loadbalancer where request's host header is set to another value than origin server is that the location header in POST responses is generated with the wrong domain in my case. Because host part is taken from host header. Maybe it makes sense to add a configuration option for the header to take the domain optionally from, e.g. in my case x-forwarded-host?

Yes, it would make sense to respect the X-Forwarded-* headers. tusd has exactly this feature already built in. However, you should also be able to configure tus-node-server to return relative URLs which do not contain the hostname using the `relativeLocation` option: https://github.com/tus/tus-node-server/blob/158b89596847e963d19b7cf3a51a20507f336eaa/lib/stores/DataStore.js#L28
