### ISSUE TITLE
Multipart Uploads to S3 fail

### ISSUE THREAD

**Issue by Emanuele-Spatola** [tus/tus-node-server#137]
I'm trying to upload files to S3 storage, I used the sample code for both client (tus-js-client) and server.
If I use `FileStore` everything works fine, but as soon as I use `S3Store` I'm not able to upload files over 12MB.
Here is the debug output (I've added 'write' and 'getOffset' logs to understand the flow):
```
tus-node-server [TusServer] handle: POST / +0ms
tus-node-server:stores:s3store bucket "s3-upload-bucket" exists +8s
tus-node-server:stores:s3store [ID] initializing multipart upload +0ms
tus-node-server:stores:s3store [ID] multipart upload created (...) +573ms
tus-node-server:stores:s3store [ID] saving metadata +0ms
tus-node-server:stores:s3store [ID] metadata file saved +658ms
tus-node-server [TusServer] handle: PATCH /files/ID +2s
tus-node-server:stores:s3store [ID] getOffset +13ms
tus-node-server:stores:s3store [ID] retrieving metadata +0ms
tus-node-server:stores:s3store [ID] metadata from s3 +0ms
tus-node-server:stores:s3store [ID] write +1s
tus-node-server:stores:s3store [ID] retrieving metadata +1ms
tus-node-server:stores:s3store [ID] metadata from cache +0ms
tus-node-server:stores:s3store [ID] finished uploading part #1 +3s
tus-node-server:stores:s3store [ID] getOffset +0ms
tus-node-server:stores:s3store [ID] retrieving metadata +0ms
tus-node-server:stores:s3store [ID] metadata from cache +0ms
```

The request stays pending and the upload does not complete unless I restart the server, in that case the upload will proceed for other 12MB. If I restart enough times the upload is completed successfully.

Please note that to achieve that result I had to add:
```javascript
app.use('/upload', function(req, res, next) {
  req.socket.server.keepAliveTimeout = 100000000000;
  req.socket.server.timeout = 100000000000;
  next();
},uploadHandler);
```
otherwise node closes the connection as it recognises it is inactive and the browser resend the PATCH with `upload-offset: 0` and I get a 409 error (`[PatchHandler] send: Incorrect offset - 0 sent but file is 8*1024*1024`)

Any idea on how I could fix this?

**Comment by saschbro** [comment]
looks like you defined different chunk sizes at client (8 mb) and server (12 mb). afaik chunk sizes have to be exactly the same at client and server otherwise uploads bigger than chunk size will not work correctly. you can set chunk size in tus-js-client by option `chunkSize` (see https://github.com/tus/tus-js-client#tusdefaultoptions).

**Comment by saschbro** [comment]
@Emanuele-Spatola happy to hear. you're welcome. i struggled the same a few days ago. so yes, in my opinion it makes absolutely sense to improve documentation 👍.

**Comment by Acconut** [comment]
I am glad to read that you were able to resolve the issue, however, it seems a bit odd to me.

> afaik chunk sizes have to be exactly the same at client and server otherwise uploads bigger than chunk size will not work correctly

I haven't tested it personally but from my understanding of the internals, the chunkSize in tus-js-client must only be bigger or equal to the partSize in tus-node-server. Since chunkSize is Infinity by default, it should not be a problem unless you change the configuration.

This all points towards a potential bug inside the S3Store, so I hope to be able to look into this soon.

**Comment by saschbro** [comment]
I tested it again and an upload of a ~70 MB file didn't work for me with chunk sizes of 12 MB for Uppy File Uploader and 8 MB for `tus-node-server`.

**Comment by Acconut** [comment]
Ok, thanks, this does not sound right. I will test it on my own and dig deeper.

**Comment by mitjap** [comment]
I looked a bit more at S3 and how it works. The issue is that S3 requires length of buffer/stream for each part that is uploaded. Since that is not known in advance current implementation guesses some value and then passes that stream to S3 library for upload. S3 will only upload at most `length` bytes and no more. If there is not enough bytes then library waits for more data until eventually timeout error is thrown.  It is implemented in such a way that each PATCH request will upload single part which is 8MB, even though user might have uploaded entire file to the server. Then when the request is complete there is usually some error that forces the client to do HEAD request and check current status. So user re-uploads file again but this time advancing for single part that just uploaded. So for file that is x MB user need to do x/8 PATCH request. 

Total upload size is ([plot](https://www.wolframalpha.com/input/?i=x*%28x%2F8%29+-+8*%28%28%28x%2F8%29*%28%28x%2F8%29-1%29%29%2F+2%29%2Cx%3D0+to+1024)):
```
// parts
p = N / 8

total = N + (N - 8) + (N - 8*2) + .... + N - (8*(p-2)) + (N - 8*(p-1))
```

Implementation should split input stream to multiple fixed sized streams and when each part is complete forward it to S3 in chunks with known length. I propose buffering to file to avoid large memory usage.

**Comment by Acconut** [comment]
> Implementation should split input stream to multiple fixed sized streams and when each part is complete forward it to S3 in chunks with known length. I propose buffering to file to avoid large memory usage.

Yes, that sounds like a good approach and is the same one as tusd uses. The upload is split into multiple parts and each part is buffered in its own file, so it can be uploaded independently. It would be amazing if tus-node-server behaves similar.

**Comment by mitjap** [comment]
Another issue is if the client parts (patches) are smaller than minimum allowed by S3 than we cant use this part. Solution is to buffer to files across multiple PATCH requests. Is this also how `tusd` works?

**Comment by Acconut** [comment]
In early version of tusd, such a part would have been discarded and the client should try to upload a larger chunk in the next PATCH request.

Now, tusd stores these incomplete parts on S3 to not discard data. When a PATCH request begins, we first fetch this incomplete part and prepend it to the request body.
