### ISSUE TITLE
Azure Storage

### ISSUE THREAD

**Issue by danvass** [tus/tus-node-server#139]
Are there any examples of using it with Azure Storage or would I have to implement it as an additional data storage provider if I wanted to use it with Tus?

**Comment by rictorres** [comment]
the latter, at the moment there's no storage provider for azure :'(

**Comment by DvdGiessen** [comment]
Since this might interest others: I also wanted to use Tus with Azure in a Node project, so I went ahead and implemented basic support for it in `tus-node-server`. See https://github.com/DvdGiessen/tus-node-server/tree/azure-blob-store.

Note that this is a work-in-progress branch. It has no tests, it most probably has bugs, it has a few quite inefficient code paths, there is barely any code documentation... in other words, use at your own risk.

I might polish it up and open a pull request later.

**Comment by Acconut** [comment]
That's amazing, @DvdGiessen! We would love to see a pull request from you for an Azure Blob Store. Let us know if we can help you.

**Comment by jaime-rivas** [comment]
Hi there! @Acconut @DvdGiessen. We are planning to migrate our uploads to tus (great project!) and I am wondering if there any updates on Azure integration. I saw that tusd added support in August 2021. Any chance that it has been added / planned to be added here to the node server too? Thanks!

**Comment by Murderlon** [comment]
We are currently working towards 1.0.0 for tus-node-server (https://github.com/tus/tus-node-server/issues/309) but Azure is not on the list. I don't expect any implementation to be in here soon. If your project is time critical, I would recommend tusd instead.

**Comment by jaime-rivas** [comment]
Thanks @Murderlon. Best wishes for the 1.0.0 release!

**Comment by Murderlon** [comment]
`@tus/azure-store` has now been published! 

Closed in #645
