### ISSUE TITLE
chunks goes to localhost:3000 even if I specify exact domain name

### ISSUE THREAD

**Issue by AlexanderKozhevin** [tus/tus-node-server#147]
I used nginx with https. 
So all requests are getting redirected.

In tus js client I specified exact URL which refer to my domain. 
But for some reason it make OPTION request to 
```
https://localhost:3000/worker/uploads/files/rich.jpg
```

Did anybody have had similar problems?

**Comment by pdiveris** [comment]
Yes, well, sort of. In my case it is redirecting to the "internal" host name (rosa) as reported by /etc/hosts rather than the hostname specified in the config block. I had to contaminate uppy with an strreplace to resolve this for now but obviously that's not a solution. I tried to find out where/how it resolves the hostname bit I didn't succeed as yet (didn't spend much time I have to admit.)

**Comment by AlexanderKozhevin** [comment]
I'm not 100% sure where the problem is coming from. 
Looks like I need to debug the source code of library and test it in different way, like you did. 

Maybe it gives wrong URL because I have server rendering with NUXT.js
Maybe not.
