### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by jazkh** [tus/tus-node-server#148]
Hello,

I am using Uppy client and tus-node-server 0.3.2 at backend.

Whenever I try to upload 12 or 15 files together, I get this error in my node server.

> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connection listeners added. Use emitter.setMaxListeners() to increase limit

How to solve this problem?

Thankyou in advance

**Comment by kvz** [comment]
From https://github.com/transloadit/uppy/issues/1455

**Comment by jazkh** [comment]
Hello kvz, 

I am using EVENT_UPLOAD_COMPLETE event.
Do i have to put setmaxlisteners 0 at the begining or end within this event?

**Comment by Acconut** [comment]
@jazkh I think you have to put this event before you are starting your server, outside of your event handler. However, this will just supress the warning instead of fixing the problem. It's not unlikely that there is a EventEmitter leak in tus-node-server but, unfortunately, don't have the resources to dig further into this. Any help would be appreciated!

**Comment by jazkh** [comment]
I have to close this issue because the problem was with the socket io which I was using within the tus node server event.
