### ISSUE TITLE
How to connect two tus severs ?

### ISSUE THREAD

**Issue by ehsanshekariTalos** [tus/tus-node-server#182]
I want to upload a file with resume capability to Cloudflare. I cannot upload a file directly from the browser to Cloudflare because the credentials should not be visible. So, I have to use tus-node-server as an express middleware on the back-end. 

I do not want to upload the file completely on my own server and after that start uploading the file to Cloudflare.  Is there a way to pipe the tus-node-server middleware to Cloudflare upload API?

**Comment by Acconut** [comment]
No, there is no such functionality to directly upload data to Cloudflare from tus-node-server. If you want to use tus-node-server, you would have to store the file somewhere before uploading it to Cloudflare.

That being said, I have seen people uploading from the browser to Cloudflare directly, so I would assume this to work without revealing secret credentials. However, I do not know more about this since I don't use Cloudflare myself.
