### ISSUE TITLE
Working with next-connect

### ISSUE THREAD

**Issue by paulm17** [tus/tus-node-server#189]
I've got this to work initially however, I'm totally stumped on how to get the tus directory serving for patch requests.

```
import { NextApiRequest, NextApiResponse } from "next"
import nc from "next-connect"

const handler = nc<NextApiRequest, NextApiResponse>()

const tus = require("tus-node-server")
const server = new tus.Server()
server.datastore = new tus.FileStore({
  path: "/files",
})

const uploadApp = nc()
uploadApp.all("*", server.handle.bind(server))
handler.use("/api/upload", uploadApp)

export default handler
```

The issue here.  Is that next-connect sets up /api/upload to be able to listen to requests, but is unaware of tus and the /files endpoint.

I've tried different things, but cannot overcome this issue.  

Any help appreciated.

Thanks

**Comment by mitjap** [comment]
For tus to correctly construct url endpoint of new upload set `path` to same prefix you use with router. For filestore you should manually set directory where files should be stored with `directory` option.

Another issue with your code is that `next-connect` modifies `url` propery of incoming request. When tus receives request it's `url` is set to `/<upload_id>` instead of `/api/upload/<upload_id>`. For this to work it is common for (express-compatible) routers to set `originalUrl` to request when they modify it.

Your working example would be
```
const server = new tus.Server()
server.datastore = new tus.FileStore({
  path: "/api/upload",
  directory: "./files",
})

const uploadApp = nc()
uploadApp.all("*", server.handle.bind(server))
handler.use("/api/upload", (req, res) => {
  req.originalUrl = '/api/upload' + req.url
  return uploadApp(req, res);
})
```

**Comment by paulm17** [comment]
Thanks for taking the time to come up with an example.
