### ISSUE TITLE
HEAD response: upload-offset and upload-length

### ISSUE THREAD

**Issue by terrischwartz** [tus/tus-node-server#21]
Looking at the example resumable upload curl commands and the tus.io protocol spec: should the response have a upload-offset header giving the amount uploaded so far and an upload-length of the full file size from the initial POST?

**Comment by bhstahl** [comment]
Gah, you're right. `DataStore#getOffset` should probably return the offset & length, so that it can be sent in the header. Looks like I'm currently sending the [length as the offset](https://github.com/tus/tus-node-server/blob/58c9f045bdc7ecf02b89043745b82a2dc7758eb1/lib/handlers/HeadHandler.js#L27-L27). Good catch @terrischwartz !
