### ISSUE TITLE
`yarn build` does not generate build files

### ISSUE THREAD

**Issue by mitjap** [tus/tus-node-server#387]
Turbo does not generate build files if there is a cache hit. `dist` folders are not generated as expected.

To reproduce this run `yarn build; git clean -Xd` (this will delete all ignored and untracked files in this folder, use with caution if there are untracked files that you want to keep) and then again `yarn build`.

```
• Packages in scope: @tus/file-store, @tus/gcs-store, @tus/s3-store, @tus/server, demo, eslint-config-custom, test, tsconfig
• Running build in 8 packages
• Remote caching disabled
@tus/server:build: Skipping cache check for @tus/server#build, outputs have not changed since previous run.
@tus/server:build: cache hit, replaying output d7264515d44699ac
@tus/file-store:build: Skipping cache check for @tus/file-store#build, outputs have not changed since previous run.
@tus/gcs-store:build: Skipping cache check for @tus/gcs-store#build, outputs have not changed since previous run.
@tus/gcs-store:build: cache hit, replaying output d2855e7818538d57
@tus/file-store:build: cache hit, replaying output 37957a470a24437a
@tus/s3-store:build: Skipping cache check for @tus/s3-store#build, outputs have not changed since previous run.
@tus/s3-store:build: cache hit, replaying output f543d9c733fc1d64

 Tasks:    4 successful, 4 total
Cached:    4 cached, 4 total
  Time:    46ms >>> FULL TURBO
```

In this case `dist` folder is not generated. I am unfamiliar with `turbo` but I think this flow should work.

**Comment by Murderlon** [comment]
Good one. There are still some issues with the mono repo setup. It was a bit of an experiment too. In all honestly, turbo is not adding a lot of value in our case, since we only have a couple small packages and it seems any change in `@tus/server` also triggers all builds as it's a dependency of the other packages. It is nice though for eslint, which is generally a slow process.

There should also be a watch mode, since tests use the build output, it's a bit annoying to always manually trigger the build before running tests.

**Comment by Murderlon** [comment]
Thinking about this again I feel running `git clean` is an edge case (I've only used it a couple times in my life) and I'm not sure what can be done about it. Furthermore, to build and test only one package quickly we can use `yarn run test --filter @tus/server`.

Closing as not actionable.
