### ISSUE TITLE
Question about purging expired files

### ISSUE THREAD

**Issue by alolis** [tus/tus-node-server#52]
Hello,

I am not sure if this has been answered/addressed already, but I couldn't find anything related. I am using the `FileStore` datastore, and I was wondering what is the recommended way (or if there is already a mechanism in place) to auto-purge expired files in order to not consume disk space.

Thank you for your time.

**Comment by bhstahl** [comment]
Hey @alolis the tus protocol includes an [Expiration](http://tus.io/protocols/resumable-upload.html#expiration) extension, however that only pertains to unfinished uploads. Since disk space management is not on the responsibility of the upload protocol, there is nothing built into tus-node-server to do that.

That said, I'm happy to help you out. Typically, the best way to do it is monitor the disk space usage of the box you're running on, and when it crosses a certain threshold, delete the oldest files. Are you planning to persist your files on this box to be uses by users/your application, or are you transferring them to something more persistent like S3 or GCS?

**Comment by alolis** [comment]
@bhstahl , thanks for your reply. I am planning to persist the files on this box.

I also have a second questions while we are at it. Does the FileStore path must be the same as the one used for the express middleware? In other words, can I do the following?

````javascript
const tus = require('tus-node-server');
const server = new tus.Server();
server.datastore = new tus.FileStore({
    **path: '/otherpath/files'**
});

var app = express();
app.all(**'/files/*'**, function(req, res) {
  server.handle(req, res);
});
app.listen(port, host);
````

**Comment by Murderlon** [comment]
Closing this as the question seems answered.
