### ISSUE TITLE
Node 7.x support

### ISSUE THREAD

**Issue by simonspoerri** [tus/tus-node-server#66]
I was not able to install tus-node-server using node 7.4.0. I received the following errors:

node-pre-gyp ERR! Tried to download: https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v0.15.0/node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@0.15.0 and node@7.4.0 (node-v51 ABI) (falling back to source compile with node-gyp) 

and building it failed too:
  CXX(target) Release/obj.target/grpc_node/src/node/ext/call.o
../src/node/ext/call.cc:616:20: error: no member named 'SetHiddenValue' in 'v8::Object'
      info.This()->SetHiddenValue(Nan::New("channel_").ToLocalChecked(),

I downgraded to node 6.9.1 and install worked just fine. This solution works for me for now but supporting the latest major node release would be nice. 

Cheers!

**Comment by bhstahl** [comment]
Hey @simonspoerri I don't think we should ever jump past the LTS version. When they upgrade it from `6.9.5` to > 7, I'm more than happy to go for it.

**Comment by doubliez** [comment]
The build fails on Node 7.x because of the outdated google-cloud dependency.

Upgrading it to `google-cloud@^0.47.0` fixed the issue for me. I don't use Google Cloud so I didn't check if this breaks the Google Cloud data store.

Would be nice if you could push a fix though, because I have a fork just for that currently. Downgrading to Node 6.x is not an option for me.

I'm also looking forward to https://github.com/tus/tus-node-server/issues/61, as I just need the core functionality so it would be great if I didn't have to install all these dependencies that I don't need.

**Comment by mitjap** [comment]
I'm closing this as Node 7.x is now end-of-life for quite some time
