### ISSUE TITLE
split upload directories

### ISSUE THREAD

**Issue by CanRau** [tus/tus-node-server#72]
hey guys..like the idea of tus and resumable uploads because connections are really sluggish here in
 perú at times..even wired connections 👍  even though at least the node server looks a little abandoned at the moment?!

am i correct that it used to support koa.js? does it still? and what version?

now to the topic, i'm splitting my upload directory in incremented folders [1, 2, 3, ...] to reduce number of files in a single folder
how can i do this using tus-node? how to create a new directory if specified limit reached? maybe checking file count on upload complete and then just passing new dir to fileServer.datastore.path ?

and I'm not yet sure how serving those files work..i can just serve them using koa of course but i try to understand tus and custom get handlers
so right now opening the url of an uploaded file won't do anything besides logging
`handle: GET /files/726e2c46be5fd77c4b8661f0a1cec62a`

any input appreciated :)

**Comment by Acconut** [comment]
> hey guys..like the idea of tus and resumable uploads because connections are really sluggish here in perú at times..even wired connections

Thank you, that's always nice to hear :)

> am i correct that it used to support koa.js? does it still? and what version?

I cannot say that for sure, since I am no Koa user on my own, but tus-node-server can be used as an Express middleware (https://github.com/tus/tus-node-server#use-tus-node-server-as-express-middleware) which can also be plugged into Koa using https://github.com/vkurchatkin/koa-connect. I haven't tried it personally but it may be worth a shot.

> now to the topic, i'm splitting my upload directory in incremented folders [1, 2, 3, ...] to reduce number of files in a single folder

Just out of curiosity: Why are you concerned about the numbers of files in a directory? Most filesystems are able to handle thousands of files in a directory without any issues.

> maybe checking file count on upload complete and then just passing new dir to fileServer.datastore.path ?

I would advise against this approach as it could conflict with some internal state. Instead, I recommend to listen for EVENT_UPLOAD_COMPLETE (https://github.com/tus/tus-node-server#events) and then move the finished upload into the specific directory where you want it to be.

> so right now opening the url of an uploaded file won't do anything besides logging

As far as I know, the default implementation does not contain a handler for GET requests (see https://github.com/tus/tus-node-server/blob/master/lib/Server.js#L75-L79). Instead, you are expect to implement it on your own (see https://github.com/tus/tus-node-server#custom-get-handlers), matching your specific use case.

Please correct me, if I am wrong, @bhstahl :)

**Comment by CanRau** [comment]
yap ookay..sounds all valid :D am going to check out koa-connect thanks for that! for now i'm fine having it separately listening..

actually just because processwire php cms is offering it...i read a little about inodes and the app is supposed to store many files as it's a media library used by multiple people (i know, it's not yet facebook and might never be...^^), and maybe because i'm over optimizing upfront..

for the get handler...wasn't too precisely i know...i've this in my code
```
fileServer.get('/files', (req, res) => {
  console.log('custom get handler', fileServer.datastore.path)
})
```
which is not doing anything..but i think i'm just doing it using koa..so nevermind

**Comment by Acconut** [comment]
Sounds good :) I am going to close this issue now as it seems your questions are answered. Feel free to open a new issues if further problems arise.

**Comment by CanRau** [comment]
thx for sharing @SavePointSam

**Comment by bhstahl** [comment]
Thanks @SavePointSam! Would you be interested in adding a koa section to the README, similar to [express](https://github.com/tus/tus-node-server#use-tus-node-server-as-express-middleware)?
