### ISSUE TITLE
working with ovh object storage?

### ISSUE THREAD

**Issue by musicformellons** [tus/tus-node-server#91]
I am a man with confidence and great plans, but limited experience, considering to setup tus-node-server and would like to use [this ovh service](https://www.ovh.co.uk/public-cloud/storage/object-storage/) which uses object storage (similar to blob storage I believe) and can be used via openstack. I have no idea if this is feasible and how easy / hard that will be. I did find [this library](https://www.npmjs.com/package/node-ovh-objectstorage) which might be helpful. Could you give me some directions if this is crazy/ totally doable and maybe some pointers. Do I need openstack or would that node-ovh-objectstorage library do the trick? Thanks!

**Comment by DragonRaider5** [comment]
It is possible, but as the package seems to only support uploading files from your local hard drive you would need to first store them, upload them and then delete them.

By forking the [node-ovh-objectstorage](https://github.com/dimer47/node-ovh-objectstorage) project, you could actually make use of streams pretty easy - just not sure about writing to an offset, you might have to implement that.

As a starting point have a look at [the original FileStore comming with tus-node-server](https://github.com/tus/tus-node-server/blob/master/lib/stores/FileStore.js). It is pretty straight forward and easy to understand (maybe with some googling regarding what the node fs functions are doing).
Just take it as a starting point and implement its functions to upload to ovh (instead of writing to your local hard drive) using your forked node-ovh-objectstorage.

Sorry about the hard to understand text, I wasn't entirely sure on how to express what I'm thinking in a structured manner ^^

Conclusion: It is possible and won't be too hard 👍

**Comment by musicformellons** [comment]
Ok! Just to be sure: By 'combining forked node-ovh-objectstorage and tus-FileStore code' I should aim for uploading straight to ovh, right? As first local download and then uploadtoOVH and delete local sounds like a serious detour.

**Comment by DragonRaider5** [comment]
Yeah, that should be the goal :)
